# Generated by Django 3.1.14 on 2022-04-11 05:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secretpath', models.CharField(max_length=200, verbose_name='シークレットパス')),
                ('message', models.TextField(verbose_name='本文')),
                ('address', models.CharField(max_length=200, verbose_name='アドレス')),
                ('image', models.ImageField(null=True, upload_to='images', verbose_name='QR画像')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='閲覧日')),
            ],
        ),
    ]
