# Generated by Django 3.1.14 on 2022-04-11 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='secretpath',
            new_name='key',
        ),
    ]
