# Generated by Django 3.1.14 on 2022-04-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220411_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='アドレス'),
        ),
    ]
