# Generated by Django 3.1.14 on 2022-04-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220411_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=30, verbose_name='名前'),
        ),
    ]
