# Generated by Django 3.1.14 on 2022-04-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220411_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='タイトル')),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True, verbose_name='サブタイトル')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('explanation1', models.TextField(verbose_name='解説1')),
                ('explanation2', models.TextField(blank=True, null=True, verbose_name='解説2')),
                ('explanation3', models.TextField(blank=True, null=True, verbose_name='解説3')),
                ('topimage1', models.ImageField(upload_to='images', verbose_name='トップ画像1')),
                ('topimage2', models.ImageField(upload_to='images', verbose_name='トップ画像2')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='名前'),
        ),
    ]
