# Generated by Django 3.1.14 on 2022-04-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220411_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='topimage1',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='トップ画像1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='topimage2',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='トップ画像2'),
        ),
    ]
