# Generated by Django 3.1.14 on 2022-04-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220411_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.IntegerField(default=0, verbose_name='カウント'),
        ),
        migrations.AddField(
            model_name='post',
            name='receiver',
            field=models.CharField(max_length=30, null=True, verbose_name='受取人'),
        ),
    ]
